-- 사용자 계정 생성
CREATE USER c##JDBC IDENTIFIED BY JDBC;

-- 접속 권한 및 테이블 생성 권한 부여
GRANT CONNECT, RESOURCE TO c##JDBC;

-- 테이블스페이스 설정
ALTER USER C##JDBC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

DROP TABLE TEST;

CREATE TABLE TEST(
    TNO NUMBER PRIMARY KEY,
    TNAME VARCHAR2(100) NOT NULL,
    TDATE DATE DEFAULT SYSDATE NOT NULL
);