

ALTER USER C##PROJECT1 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE TABLE menu (
    id INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    category VARCHAR(20),
    price INT NOT NULL
);


CREATE TABLE member (
    phone_number VARCHAR2(20) PRIMARY KEY,
    stamp_count NUMBER DEFAULT 0,
    has_coupon CHAR(1) DEFAULT 'N' CHECK (has_coupon IN ('Y', 'N'))
);



CREATE TABLE Orders (
    order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    phone VARCHAR2(20),
    order_date DATE NOT NULL,
    show_order CLOB,
    total_price NUMBER(10, 2) NOT NULL,
    status VARCHAR2(50)
);


select * from menu;
select * from orders;
select * from member;


DELETE FROM orders;
CREATE TABLE Orders (
    phone VARCHAR2(20) PRIMARY KEY,
    order_date DATE NOT NULL,
    show_order CLOB,
    total_price NUMBER(10, 2) NOT NULL,
    status VARCHAR2(50)
);




insert into menu values ( 1, '아메리카노' , '커피', 4000);
insert into menu values ( 2, '카페라떼' , '커피', 4500);
insert into menu values ( 3, '카푸치노' , '커피', 4500);
insert into menu values ( 4, '바닐라 라떼' , '커피', 5000);
insert into menu values ( 5, '카페 모카' , '커피', 5000);
insert into menu values ( 6, '캐러멜 마키야토' , '커피', 5500);
insert into menu values ( 7, '에스프레소' , '커피', 5500);
INSERT INTO menu (id, name, category, price) VALUES (101, '밀크티', 'tea', 4000);
INSERT INTO menu (id, name, category, price) VALUES (102, '녹차', 'tea', 4500);
INSERT INTO menu (id, name, category, price) VALUES (103, '로즈마리', 'tea', 4500);
INSERT INTO menu (id, name, category, price) VALUES (104, '자스민', 'tea', 5000);
INSERT INTO menu (id, name, category, price) VALUES (105, '페퍼민트', 'tea', 5000);
INSERT INTO menu (id, name, category, price) VALUES (106, '유자차', 'tea', 5500);
INSERT INTO menu (id, name, category, price) VALUES (107, '레몬티', 'tea', 5500);
INSERT INTO menu (id, name, category, price) VALUES (201, '레몬아이스티', 'non-Coffee', 4000);
INSERT INTO menu (id, name, category, price) VALUES (202, '미숫가루', 'non-Coffee', 4500);
INSERT INTO menu (id, name, category, price) VALUES (203, '밀크티라떼', 'non-Coffee', 4500);
INSERT INTO menu (id, name, category, price) VALUES (204, '말차라떼', 'non-Coffee', 5000);
INSERT INTO menu (id, name, category, price) VALUES (205, '초코라떼', 'non-Coffee', 5000);
INSERT INTO menu (id, name, category, price) VALUES (206, '딸기라떼', 'non-Coffee', 5500);

commit;
drop table orders CASCADE CONSTRAINTS;
drop table orders_item CASCADE CONSTRAINTS;

