-- 샘플 데이터 입력 스크립트
-- 무인편의점 키오스크 테스트용

-- 샘플 상품 데이터
INSERT INTO PRODUCT (PROD_ID, NAME, CATEGORY, PRICE, STOCK_QTY, IS_PERISHABLE, EXPIRY_DATE, ON_SALE_YN)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '삼다수 500ml', '음료', 1200, 100, 'N', NULL, 'Y');

INSERT INTO PRODUCT (PROD_ID, NAME, CATEGORY, PRICE, STOCK_QTY, IS_PERISHABLE, EXPIRY_DATE, ON_SALE_YN)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '새우깡', '과자', 2500, 50, 'N', NULL, 'Y');

INSERT INTO PRODUCT (PROD_ID, NAME, CATEGORY, PRICE, STOCK_QTY, IS_PERISHABLE, EXPIRY_DATE, ON_SALE_YN)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '삼각김밥(참치)', '즉석식품', 1800, 30, 'Y', TO_DATE('2025-08-30', 'YYYY-MM-DD'), 'Y');

INSERT INTO PRODUCT (PROD_ID, NAME, CATEGORY, PRICE, STOCK_QTY, IS_PERISHABLE, EXPIRY_DATE, ON_SALE_YN)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '신라면', '라면', 1000, 80, 'N', NULL, 'Y');

INSERT INTO PRODUCT (PROD_ID, NAME, CATEGORY, PRICE, STOCK_QTY, IS_PERISHABLE, EXPIRY_DATE, ON_SALE_YN)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '바나나우유', '음료', 1500, 25, 'Y', TO_DATE('2025-09-01', 'YYYY-MM-DD'), 'Y');

-- 샘플 회원 데이터
INSERT INTO MEMBER (USERNO, NAME, PHONE, POINT_BALANCE, JOIN_DATE)
VALUES (SEQ_USERNO.NEXTVAL, '홍길동', '010-1234-5678', 0, SYSDATE);

INSERT INTO MEMBER (USERNO, NAME, PHONE, POINT_BALANCE, JOIN_DATE)
VALUES (SEQ_USERNO.NEXTVAL, '김영희', '010-9876-5432', 500, SYSDATE);

COMMIT;