-- 사용자 계정 생성
--CREATE USER C##LIFEGAME IDENTIFIED BY LIFEGAME;
-- 접속 권한 및 테이블 생성 권한 부여
--GRANT CONNECT, RESOURCE TO C##LIFEGAME;
-- 테이블스페이스 설정
--ALTER USER C##LIFEGAME DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


DROP TABLE USER_ACHIEVEMENT;
DROP TABLE ACHIEVEMENT_LIST;
DROP TABLE STOCK;
DROP TABLE LIFE_CHARACTER;
DROP TABLE USER_TABLE;
DROP SEQUENCE CHARACTER_SEQ;

CREATE TABLE USER_TABLE(
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_PW VARCHAR2(40) NOT NULL
);
CREATE SEQUENCE CHARACTER_SEQ 
NOCACHE;

CREATE TABLE LIFE_CHARACTER(
    CHARACTER_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL,
    CHARACTER_NAME VARCHAR2(30) NOT NULL,
    AGE NUMBER DEFAULT 20,
    MONEY NUMBER DEFAULT 1000,
    INTELLIGENCE NUMBER DEFAULT 5,
    STAMINA NUMBER DEFAULT 3,
    LUCK NUMBER DEFAULT 5,
    
    -- 각 직업별 경력
    PART_TIME_EXP NUMBER DEFAULT 0,
    EMPLOYEE_EXP NUMBER DEFAULT 0,
    EXECUTIVE_EXP NUMBER DEFAULT 0,
    ENTREPRENEUR_EXP NUMBER DEFAULT 0,
    LABORER_EXP NUMBER DEFAULT 0,
    SUPERVISOR_EXP NUMBER DEFAULT 0,
    TRAINER_EXP NUMBER DEFAULT 0,
    ATHLETE_EXP NUMBER DEFAULT 0,
    
    -- 투자 관련
    STOCK_COUNT NUMBER DEFAULT 0,
    STOCK_VALUE NUMBER DEFAULT 0,
    HAS_APARTMENT NUMBER DEFAULT 0,
    HAS_BUILDING NUMBER DEFAULT 0,
    HAS_HOTEL NUMBER DEFAULT 0,
    
    FOREIGN KEY (USER_ID) REFERENCES USER_TABLE(USER_ID)
);

CREATE TABLE ACHIEVEMENT_LIST(
    ACHIEVEMENT_ID NUMBER PRIMARY KEY,
    ACHIEVEMENT_TITLE VARCHAR2(100) NOT NULL,
    ACHIEVEMENT_DESCRIBE VARCHAR2(200) NOT NULL
);

INSERT INTO ACHIEVEMENT_LIST VALUES (1, '꽃다운 나이에... 안타깝네', '30세 이전에 사망');
INSERT INTO ACHIEVEMENT_LIST VALUES (2, '인생사 공수레 공수거', '최종 자산 0원');
INSERT INTO ACHIEVEMENT_LIST VALUES (3, '나는야 건물주', '아파트, 빌딩, 호텔 모두 보유');
INSERT INTO ACHIEVEMENT_LIST VALUES (4, '편한 일이 최고야', '아르바이트 경력 50년 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (5, '임직원 외길 인생', '회사원 경력 50년 이상 (임원/창업자 경험 없음)');
INSERT INTO ACHIEVEMENT_LIST VALUES (6, '백만장자', '최종 자산 10억원 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (7, '억소리나는 인생', '최종 자산 100억원 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (8, '천재', '지능 300 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (9, '금강불괴', '체력 600 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (10, '노가다의 신', '노가다 경력 75년 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (11, '짐종국', '트레이너 경력 40년 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (12, 'Do you Know Club', '운동선수 경력 30년 이상 + 최종 재산 150억원 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (13, '로또 주식회사 파산', '운 스탯 1990 이상');
INSERT INTO ACHIEVEMENT_LIST VALUES (14, '떡상 가즈아!!!!!', '보유 주식 총 가치 100억 이상');

CREATE TABLE USER_ACHIEVEMENT (
    ACHIEVEMENT_ID NUMBER,
    USER_ID VARCHAR2(20),
    IS_ACHIEVE NUMBER(1) DEFAULT 0,
    PRIMARY KEY (USER_ID, ACHIEVEMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER_TABLE(USER_ID),
    FOREIGN KEY (ACHIEVEMENT_ID) REFERENCES ACHIEVEMENT_LIST(ACHIEVEMENT_ID)
);

CREATE TABLE STOCK(
	CHARACTER_ID NUMBER REFERENCES LIFE_CHARACTER(CHARACTER_ID),
    PRICE NUMBER DEFAULT 500
);

COMMIT;



