DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    USER_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(20) UNIQUE NOT NULL,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(21) NOT NULL,
    USER_GENDER CHAR(1) CHECK(USER_GENDER IN('F','M')),
    USER_NICKNAME VARCHAR2(30) NOT NULL,
    USER_EMAIL VARCHAR2(100)
);

DROP SEQUENCE SEQ_MEMNO;

CREATE SEQUENCE SEQ_MEMNO;

--더미 데이터
INSERT INTO MEMBER 
VALUES(SEQ_MEMNO.NEXTVAL, 'user01', 'pass01', '홍길동', 'M', '홍길동', 'user01@naver.com');
INSERT INTO MEMBER 
VALUES(SEQ_MEMNO.NEXTVAL, 'user02', 'pass02', '유재석', 'M', '메뚜기', 'yjs02@naver.com');
INSERT INTO MEMBER 
VALUES(SEQ_MEMNO.NEXTVAL, 'user03', 'pass03', '아이유', 'F', 'IU', 'IU03@naver.com');