CREATE TABLE MEMBER(
USER_NO NUMBER PRIMARY KEY,
USER_ID VARCHAR(20) NOT NULL UNIQUE,
USER_NAME VARCHAR(50) NOT NULL,
USER_AGE NUMBER NOT NULL
);

DROP TABLE MEMBER;

CREATE TABLE MOVIE(
MOVIE_NO NUMBER PRIMARY KEY,
MOVIE_NAME VARCHAR2(100) NOT NULL,
MOVIE_GENRE VARCHAR2(50) NOT NULL,
MOVIE_AGE NUMBER
);

DROP TABLE MEMBER;

CREATE TABLE RATE(
RATE_NO NUMBER PRIMARY KEY,
RATE_USER_NO REFERENCES MEMBER(USER_NO) ON DELETE CASCADE,
RATE_MOVIE_NO REFERENCES MOVIE(MOVIE_NO) ON DELETE CASCADE,
RATE_MOVIE_SCORE NUMBER CHECK(RATE_MOVIE_SCORE IN(1,2,3,4,5)),
RATE_MOVIE_COMMENT VARCHAR2(200)
);

CREATE SEQUENCE MEMBER_SEQ_NO
NOCYCLE
NOCACHE;

CREATE SEQUENCE MOVIE_SEQ_NO
NOCYCLE
NOCACHE;

CREATE SEQUENCE RATE_SEQ_NO
NOCYCLE
NOCACHE;
