DROP TABLE DECK;
DROP TABLE SIN_TABLE;

CREATE TABLE SIN_TABLE(
    IDEN_NO NUMBER PRIMARY KEY, --인격번호
    --수감자 / 시즌 / 레어도 / 인격순서 예시) 이상 1 00 1 01
    CHAR_NO NUMBER CONSTRAINT CHNO_NN NOT NULL CONSTRAINT CHNO_CH CHECK(CHAR_NO IN (1,2,3,4,5,6,7,8,9,11,12,13)),
    --수감자 번호
    IDEN_NAME VARCHAR2(100) CONSTRAINT IDBA_NN NOT NULL, --인격이름
    SEASON NUMBER NOT NULL, --시즌
    RARITY NUMBER NOT NULL, --희귀도
    
    HP NUMBER CONSTRAINT HP_NN NOT NULL, --체력
    SPEED_MIN NUMBER CONSTRAINT SP_MIN_NN NOT NULL, --최저속도
    SPEED_MAX NUMBER CONSTRAINT SP_MAX_NN NOT NULL, --최고속도
    HIT_LEVEL NUMBER CONSTRAINT HTLE_NN NOT NULL, --방어레벨보정
    HIT_SLASH NUMBER CONSTRAINT HTSL_NN NOT NULL CONSTRAINT HTSL_CH CHECK(HIT_SLASH IN (2, 1, 0, -1)),
    --참격내성
    HIT_PENE NUMBER CONSTRAINT HTPE_NN NOT NULL CONSTRAINT HTPE_CH CHECK(HIT_PENE IN (2, 1, 0, -1)),
    --관통내성
    HIT_BLOW NUMBER CONSTRAINT HTBL_NN NOT NULL CONSTRAINT HTBK_CH CHECK(HIT_BLOW IN (2, 1, 0, -1)),
    --타격내성
    
    FIR_NAME VARCHAR2(100) CONSTRAINT FINA_NN NOT NULL, --1스킬 이름
    FIR_SIN NUMBER CONSTRAINT FISI_NN NOT NULL CONSTRAINT FISI_CH CHECK(FIR_SIN IN (1,2,3,4,5,6,7)),
    --1스킬 죄악속성 --1)분노 2)색욕 3)나태 4)탐식 5)우울 6)오만 7)질투
    FIR_TYPE NUMBER CONSTRAINT FITP_NN NOT NULL CONSTRAINT FITP_CH CHECK(FIR_TYPE IN (1,2,3)),
    --1스킬 공격유형 --1)참격 2)관통 3)타격
    FIR_LEVEL NUMBER CONSTRAINT FILV_NN NOT NULL, --1스킬 공격레벨보정
    FIR_COIN_MANY NUMBER CONSTRAINT FICM_NN NOT NULL, --1스킬 코인갯수
    FIR_BASE NUMBER CONSTRAINT FIBS_NN NOT NULL, --1스킬 기본위력
    FIR_COIN NUMBER CONSTRAINT FICO_NN NOT NULL, --1스킬 코인위력
    
    SEC_NAME VARCHAR2(100) CONSTRAINT SENA_NN NOT NULL, --2스킬 이름
    SEC_SIN NUMBER CONSTRAINT SESI_NN NOT NULL CONSTRAINT SESI_CH CHECK(SEC_SIN IN (1,2,3,4,5,6,7)),
    --2스킬 죄악속성 --1)분노 2)색욕 3)나태 4)탐식 5)우울 6)오만 7)질투
    SEC_TYPE NUMBER CONSTRAINT SETP_NN NOT NULL CONSTRAINT SETP_CH CHECK(SEC_TYPE IN (1,2,3)),
    --2스킬 공격유형 --1)참격 2)관통 3)타격
    SEC_LEVEL NUMBER CONSTRAINT SELV_NN NOT NULL, --2스킬 공격레벨보정
    SEC_COIN_MANY NUMBER CONSTRAINT SECM_NN NOT NULL, --2스킬 코인갯수
    SEC_BASE NUMBER CONSTRAINT SEBS_NN NOT NULL, --2스킬 기본위력
    SEC_COIN NUMBER CONSTRAINT SECO_NN NOT NULL, --2스킬 코인위력
    
    THI_NAME VARCHAR2(100) CONSTRAINT THNA_NN NOT NULL, --3스킬 이름
    THI_SIN NUMBER CONSTRAINT THSI_NN NOT NULL CONSTRAINT THSI_CH CHECK(THI_SIN IN (1,2,3,4,5,6,7)),
    --3스킬 죄악속성 --1)분노 2)색욕 3)나태 4)탐식 5)우울 6)오만 7)질투
    THI_TYPE NUMBER CONSTRAINT THTP_NN NOT NULL CONSTRAINT THTP_CH CHECK(THI_TYPE IN (1,2,3)),
    --3스킬 공격유형 --1)참격 2)관통 3)타격
    THI_LEVEL NUMBER CONSTRAINT THLV_NN NOT NULL, --3스킬 공격레벨보정
    THI_COIN_MANY NUMBER CONSTRAINT THCM_NN NOT NULL, --3스킬 코인갯수
    THI_BASE NUMBER CONSTRAINT THBS_NN NOT NULL, --3스킬 기본위력
    THI_COIN NUMBER CONSTRAINT THCO_NN NOT NULL, --3스킬 코인위력
    
    DEF_NAME VARCHAR2(100) CONSTRAINT DENA_NN NOT NULL, --수비스킬 이름
    DEF_SIN NUMBER CONSTRAINT DESI_NN NOT NULL CONSTRAINT DESI_CH CHECK(DEF_SIN IN (1,2,3,4,5,6,7)),
    --방어스킬 죄악속성 --1)분노 2)색욕 3)나태 4)탐식 5)우울 6)오만 7)질투
    DEF_TYPE NUMBER CONSTRAINT DETP_NN NOT NULL CONSTRAINT DETP_CH CHECK(DEF_TYPE IN (1,2,3,4,5)),
    --방어스킬 방어타입 --1)방어 2)회피 3)반격 4)강화방어 5)강화반격
    DEF_LEVEL NUMBER CONSTRAINT DELV_NN NOT NULL, --방어스킬 수비레벨보정
    DEF_COIN_MANY NUMBER CONSTRAINT DECM_NN NOT NULL, --방어스킬 코인갯수
    DEF_BASE NUMBER CONSTRAINT DEBS_NN NOT NULL, --방어스킬 기본위력
    DEF_COIN NUMBER CONSTRAINT DECO_NN NOT NULL, --방어스킬 코인위력
    
    PAS_NAME VARCHAR2(100) CONSTRAINT PANA_NN NOT NULL, --패시브 이름
    PAS_KIND NUMBER CONSTRAINT PAKN_NN NOT NULL CONSTRAINT PAKN_CH CHECK(PAS_KIND IN (1,2)),
    --패시브 요구 죄악종류
    PAS_SIN NUMBER CONSTRAINT PASI_NN NOT NULL CONSTRAINT PASI_CH CHECK(PAS_SIN IN (1,2,3,4,5,6,7)),
    --패시브 요구 죄악속성 --1)분노 2)색욕 3)나태 4)탐식 5)우울 6)오만 7)질투
    PAS_SIN_SEC NUMBER CONSTRAINT PASI_SE_CH CHECK(PAS_SIN_SEC IN (1,2,3,4,5,6,7)),
    --패시브 요구 죄악속성 (두번째)
    PAS_TYPE NUMBER CONSTRAINT PATP_NN NOT NULL CONSTRAINT PATP_CH CHECK(PAS_TYPE IN (1,2)),
    --패시브 타입 --1)보유 2)공명
    PAS_MANY NUMBER CONSTRAINT PAMN_NN NOT NULL, --패시브 요구 죄악갯수
    PAS_MANY_SEC NUMBER, --패시브 요구 죄악갯수 (두번째)
    
    SUP_NAME VARCHAR2(100) CONSTRAINT SPNA_NN NOT NULL, --서포트 패시브 이름
    SUP_KIND NUMBER CONSTRAINT SPKN_NN NOT NULL CONSTRAINT SPKN_CH CHECK(SUP_KIND IN (1,2)),
    --서포트 요구 죄악종류
    SUP_SIN NUMBER CONSTRAINT SPSI_NN NOT NULL CONSTRAINT SPSI_CH CHECK(SUP_SIN IN (1,2,3,4,5,6,7)),
    --서포트 요구 죄악속성
    SUP_SIN_SEC NUMBER CONSTRAINT SPSI_SE_CH CHECK(SUP_SIN_SEC IN (1,2,3,4,5,6,7)),
    --서포트 요구 죄악속성 (두번째)
    SUP_TYPE NUMBER CONSTRAINT SPTP_NN NOT NULL CONSTRAINT SPTP_CH CHECK(SUP_TYPE IN (1,2)),
    --서포트 타입 --1)보유 2)공명
    SUP_MANY NUMBER CONSTRAINT SPMN_NN NOT NULL, --서포트 요구 죄악갯수
    SUP_MANY_SEC NUMBER, --서포트 요구 죄악갯수 (두번째)
    
    RELATION VARCHAR2(300),
    
    KEYWORD VARCHAR2(300)
);

COMMENT ON COLUMN SIN_TABLE.IDEN_NO IS '인격번호';
COMMENT ON COLUMN SIN_TABLE.CHAR_NO IS '수감자번호';
COMMENT ON COLUMN SIN_TABLE.IDEN_NAME IS '인격이름'; 
COMMENT ON COLUMN SIN_TABLE.SEASON IS '시즌';
COMMENT ON COLUMN SIN_TABLE.RARITY IS '희귀도';
    
COMMENT ON COLUMN SIN_TABLE.HP IS '체력';
COMMENT ON COLUMN SIN_TABLE.SPEED_MIN IS '최저속도';
COMMENT ON COLUMN SIN_TABLE.SPEED_MAX IS '최고속도';
COMMENT ON COLUMN SIN_TABLE.HIT_LEVEL IS '방어레벨보정';
COMMENT ON COLUMN SIN_TABLE.HIT_SLASH IS '참격내성';
COMMENT ON COLUMN SIN_TABLE.HIT_PENE IS '관통내성';
COMMENT ON COLUMN SIN_TABLE.HIT_BLOW IS '타격내성';
    
COMMENT ON COLUMN SIN_TABLE.FIR_NAME IS '1스킬 이름';
COMMENT ON COLUMN SIN_TABLE.FIR_SIN IS '1스킬 죄악속성';
COMMENT ON COLUMN SIN_TABLE.FIR_TYPE IS '1스킬 공격유형';
COMMENT ON COLUMN SIN_TABLE.FIR_LEVEL IS '1스킬 공격레벨보정';
COMMENT ON COLUMN SIN_TABLE.FIR_COIN_MANY IS '1스킬 코인갯수';
COMMENT ON COLUMN SIN_TABLE.FIR_BASE IS '1스킬 기본위력';
COMMENT ON COLUMN SIN_TABLE.FIR_COIN IS '1스킬 코인위력';

COMMENT ON COLUMN SIN_TABLE.SEC_NAME IS '2스킬 이름';
COMMENT ON COLUMN SIN_TABLE.SEC_SIN IS '2스킬 죄악속성';
COMMENT ON COLUMN SIN_TABLE.SEC_TYPE IS '2스킬 공격유형';
COMMENT ON COLUMN SIN_TABLE.SEC_LEVEL IS '2스킬 공격레벨보정';
COMMENT ON COLUMN SIN_TABLE.SEC_COIN_MANY IS '2스킬 코인갯수';
COMMENT ON COLUMN SIN_TABLE.SEC_BASE IS '2스킬 기본위력';
COMMENT ON COLUMN SIN_TABLE.SEC_COIN IS '2스킬 코인위력';

COMMENT ON COLUMN SIN_TABLE.THI_NAME IS '3스킬 이름';
COMMENT ON COLUMN SIN_TABLE.THI_SIN IS '3스킬 죄악속성';
COMMENT ON COLUMN SIN_TABLE.THI_TYPE IS '3스킬 공격유형';
COMMENT ON COLUMN SIN_TABLE.THI_LEVEL IS '3스킬 공격레벨보정';
COMMENT ON COLUMN SIN_TABLE.THI_COIN_MANY IS '3스킬 코인갯수';
COMMENT ON COLUMN SIN_TABLE.THI_BASE IS '3스킬 기본위력';
COMMENT ON COLUMN SIN_TABLE.THI_COIN IS '3스킬 코인위력';

COMMENT ON COLUMN SIN_TABLE.DEF_NAME IS '수비스킬 이름';
COMMENT ON COLUMN SIN_TABLE.DEF_SIN IS '수비스킬 죄악속성';
COMMENT ON COLUMN SIN_TABLE.DEF_TYPE IS '수비스킬 방어타입';
COMMENT ON COLUMN SIN_TABLE.DEF_LEVEL IS '수비스킬 수비레벨보정';
COMMENT ON COLUMN SIN_TABLE.DEF_COIN_MANY IS '수비스킬 코인갯수';
COMMENT ON COLUMN SIN_TABLE.DEF_BASE IS '수비스킬 기본위력';
COMMENT ON COLUMN SIN_TABLE.DEF_COIN IS '수비스킬 코인위력';

COMMENT ON COLUMN SIN_TABLE.PAS_NAME IS '패시브 이름';
COMMENT ON COLUMN SIN_TABLE.PAS_KIND IS '패시브 죄악종류';
COMMENT ON COLUMN SIN_TABLE.PAS_SIN IS '패시브 죄악속성';
COMMENT ON COLUMN SIN_TABLE.PAS_SIN_SEC IS '패시브 죄악속성(2)';
COMMENT ON COLUMN SIN_TABLE.PAS_TYPE IS '패시브 타입';
COMMENT ON COLUMN SIN_TABLE.PAS_MANY IS '패시브 죄악갯수';
COMMENT ON COLUMN SIN_TABLE.PAS_MANY_SEC IS'패시브 죄악갯수(2)';

COMMENT ON COLUMN SIN_TABLE.SUP_NAME IS '서포트 패시브 이름';   
COMMENT ON COLUMN SIN_TABLE.SUP_KIND IS '서포트 죄악종류';
COMMENT ON COLUMN SIN_TABLE.SUP_SIN IS '서포트 죄악속성';
COMMENT ON COLUMN SIN_TABLE.SUP_SIN_SEC IS '서포트 죄악속성 (2)';
COMMENT ON COLUMN SIN_TABLE.SUP_TYPE IS '서포트 타입';
COMMENT ON COLUMN SIN_TABLE.SUP_MANY IS '서포트 죄악갯수';
COMMENT ON COLUMN SIN_TABLE.SUP_MANY_SEC IS '서포트 죄악갯수 (2)';

COMMENT ON COLUMN SIN_TABLE.RELATION IS '소속';

COMMENT ON COLUMN SIN_TABLE.KEYWORD IS '키워드';
